### PR TITLE
Fix End of the World purple eyes HFR

### LINKED ISSUE #105: End of the World purple eyes suck too fast at HFR
### Description

https://github.com/user-attachments/assets/8a9a9eb0-0c97-4b7b-b060-c19de15a46ef

### PR DESCRIPTION
**Pull request by ReimousTH**
Closes #105.

### CODE REVIEW

File: MarathonRecomp/api/Sonicteam/SoX/MessageReceiver.h [hunk 1]
```diff
@@ -1,22 +1,24 @@
...
         {
-            be<uint32_t> OnMessageRecieved;
+            be<uint32_t> fpDestroy;
+            be<uint32_t> fpOnMessageRecieved;
         };
 
         xpointer<Vftable> m_pVftable;
 
-        bool OnMessageRecieved(Message* message)
+        bool OnMessageRecieved(IMessage* pMessage)
```
Comment (KohlsAdrian) [inline MarathonRecomp/api/Sonicteam/SoX/MessageReceiver.h]: `onMessageReceived`

Comment (hyperbx) [reply MarathonRecomp/api/Sonicteam/SoX/MessageReceiver.h]: Corrected the typo, the API does not use camelCase for public method names.

**Review by IsaacMarovitz — APPROVED** [review]
