### PR TITLE
Fix Particle Framerate for HFR

### LINKED ISSUE #38: Particle effects are amplified at HFR
Various particle effects (e.g. spin dash, grind particles, etc.) create particles too fast at HFR, causing them to emit way more than they should exponentially as the frame rate increases.

### PR DESCRIPTION
**Pull request by ReimousTH**
Closes #38.

### CODE REVIEW

File: MarathonRecomp/patches/fps_patches.cpp [hunk 1]
```diff
@@ -121,3 +123,29 @@ void PlayerObject_ProcessMsgSuckPlayer_FixDeltaTime(PPCRegister& message, PPCReg
 
     deltaTime.f64 = pMessage->DeltaTime;
 }
+//not need anything here
+void ParticleHFR_826454C8(PPCRegister& f31)
```
Comment (IsaacMarovitz) [inline MarathonRecomp/patches/fps_patches.cpp]: If this patch is just being used as a NOP, then please remove this function and use the `NOP` one.

File: MarathonRecomp/patches/fps_patches.cpp [hunk 2]
```diff
@@ -1,5 +1,7 @@
 #include <api/Marathon.h>
 #include <user/config.h>
+#include <app.h>
+
```
Comment (IsaacMarovitz) [inline MarathonRecomp/patches/fps_patches.cpp:4]: Extra whitespace

File: MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h [hunk 3]
```diff
@@ -0,0 +1,14 @@
+#pragma once
+
+#include <Sonicteam/System/Singleton.h>
+#include <Sonicteam/System/CreateStatic.h>
+
+namespace Sonicteam::System::Diagnostic
+{
+
+    class Perfomance:public Singleton<Perfomance,0x82D3B210,CreateStatic<Perfomance,0x82581C88>>
```
Comment (hyperbx) [inline MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h]:
```suggestion
    class Perfomance : public Singleton<Perfomance, 0x82D3B210, CreateStatic<Perfomance, 0x82581C88>>
```

File: MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h [hunk 4]
```diff
@@ -0,0 +1,14 @@
+#pragma once
+
+#include <Sonicteam/System/Singleton.h>
+#include <Sonicteam/System/CreateStatic.h>
+
+namespace Sonicteam::System::Diagnostic
+{
+
```
Comment (hyperbx) [inline MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h]: Extra white space.

File: MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h [hunk 5]
```diff
@@ -0,0 +1,14 @@
+#pragma once
+
+#include <Sonicteam/System/Singleton.h>
+#include <Sonicteam/System/CreateStatic.h>
+
+namespace Sonicteam::System::Diagnostic
```
Comment (hyperbx) [inline MarathonRecomp/api/Sonicteam/System/Diagnostic/Perfomance.h]: Isn't this namespace supposed to be `Diagnostics` instead of `Diagnostic`?

File: MarathonRecomp/api/Marathon.h [hunk 6]
```diff
@@ -136,6 +136,7 @@
 #include "Sonicteam/StdImageFilters/BurnoutBlurFilter.h"
 #include "Sonicteam/StdImageFilters/SingleTechniqueFilter.h"
 #include "Sonicteam/System/CreateStatic.h"
+#include "Sonicteam/System/Diagnostic/Perfomance.h"
```
Comment (hyperbx) [inline MarathonRecomp/api/Marathon.h]: Make sure to change this file location if renaming from `Diagnostic` to `Diagnostics`.

File: MarathonRecompLib/config/Marathon.toml [hunk 7]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
...
+[[midasm_hook]]
+name = "ParticleHFR_826454C8"
+address = 0x82645518 
+registers = ["f31"]
+jump_address = 0x8264551C
+
+[[midasm_hook]]
+name = "ParticleHFR_82670658"
+address = 0x82670724 
+registers = ["f1","r1"]
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]:
```suggestion
registers = ["f1", "r1"]
```

File: MarathonRecompLib/config/Marathon.toml [hunk 8]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
...
+after_instruction = true
+
+[[midasm_hook]]
+name = "ParticleHFR_8266A418_1"
+address = 0x8266A57C 
+registers = ["f31","r1"]
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]:
```suggestion
registers = ["f31", "r1"]
```

File: MarathonRecompLib/config/Marathon.toml [hunk 9]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
...
+after_instruction = true
+
+[[midasm_hook]]
+name = "ParticleHFR_82673F88"
+address = 0x8267402C 
+registers = ["f13","r1"]
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]:
```suggestion
registers = ["f13", "r1"]
```

File: MarathonRecompLib/config/Marathon.toml [hunk 10]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
...
+after_instruction = true
+
+[[midasm_hook]]
+name = "ParticleHFR_82674550"
+address = 0x826747FC 
+registers = ["f13","r1"]
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]:
```suggestion
registers = ["f13", "r1"]
```

File: MarathonRecompLib/config/Marathon.toml [hunk 11]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
 name = "PlayerObject_ProcessMsgSuckPlayer_FixDeltaTime"
 address = 0x8219B660
 registers = ["r28", "f31"]
+
+[[midasm_hook]]
+name = "ParticleHFR_826454C8"
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]: See https://github.com/sonicnext-dev/MarathonRecomp/pull/160/files#r2349206481.

```suggestion
name = "NOP"
```

File: MarathonRecompLib/config/Marathon.toml [hunk 12]
```diff
@@ -508,3 +508,33 @@ registers = ["r28", "f1"]
...
+address = 0x82645518 
+registers = ["f31"]
```
Comment (hyperbx) [inline MarathonRecompLib/config/Marathon.toml]:
```suggestion

```

**Review by hyperbx — CHANGES_REQUESTED** [review]

File: MarathonRecompLib/config/Marathon.toml [hunk 13]
```diff
@@ -538,3 +568,4 @@ registers = ["f31", "f1"]
 name = "HUDWindow_Callback"
 address = 0x824FA088
 registers = ["f1", "f31"]
+
```
Comment (IsaacMarovitz) [inline MarathonRecompLib/config/Marathon.toml]: Extra whitespace, include EOF but not any more lines than that.

File: MarathonRecompLib/config/Marathon.toml [hunk 14]
```diff
@@ -509,6 +509,36 @@ name = "PlayerObject_ProcessMsgSuckPlayer_FixDeltaTime"
 address = 0x8219B660
 registers = ["r28", "f31"]
 
+#ParticleHFR_826454C8
```
Comment (IsaacMarovitz) [inline MarathonRecompLib/config/Marathon.toml]: Add a space after `#`

File: MarathonRecompLib/config/Marathon.toml (hunk 13 above)
Comment (ReimousTH) [reply MarathonRecompLib/config/Marathon.toml]: ???
